In [1]:
import numpy as np

In [2]:
# 设置seed, 使得多次生成的随机数相同
np.random.seed(seed=1234)

In [3]:
x = np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x size: ", x.size)
print("x shape: ", x.shape)
print("x dtype: ", x.dtype)

x:  6
x ndim:  0
x size:  1
x shape:  ()
x dtype:  int64


In [4]:
x = np.array([1.3, 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x size: ", x.size)
print("x shape: ", x.shape)
print("x dtype: ", x.dtype)

x:  [1.3 2.2 1.7]
x ndim:  1
x size:  3
x shape:  (3,)
x dtype:  float64


In [5]:
# 三位数组 (矩阵matrix)
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [6]:
print("np.zeros((3,3)): \n", np.zeros((3,3)))
print("np.ones((3,3)): \n", np.ones((3,3)))
print("np.eye(3,3): \n", np.eye(3,3))
print("np.random.random(2,2): \n", np.random.random((2,2)))

np.zeros((3,3)): 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)): 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye(3,3): 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random(2,2): 
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [7]:
np.random.randn(2,2)

array([[-0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ]])

In [8]:
np.random.randint(1,10)

7

In [9]:
# 索引 (Indexing)
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [10]:
x = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]
             ])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1,2 & cols 1,2: \n", x[:3, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [11]:
x[2:3, 1:3]


array([[10, 11]])

In [12]:
x[2, 1:3]

array([10, 11])

In [13]:
len(x)

3

In [14]:
# 整数数组索引
print (x)
rows_to_get = np.arange(len(x))
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
print ("indexed values: ", x[rows_to_get, cols_to_get])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [15]:
x = np.array([[1,2], [3, 4], [5, 6]])
print("x: \n", x)
print("x > 2: \n", x>2)
print("x[x>2]: \n", x[x>2])

x: 
 [[1 2]
 [3 4]
 [5 6]]
x > 2: 
 [[False False]
 [ True  True]
 [ True  True]]
x[x>2]: 
 [3 4 5 6]


In [16]:
# 基本运算
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print("x + y:\n", np.add(x, y)) # 加
print("x - y:\n", np.subtract(x, y)) # 减
print("x * y:\n", np.multiply(x, y)) # 乘

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


In [17]:
# 点乘 (Dot Product)
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # 我们可以指定dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
print(a.dot(b))

[[ 58.  64.]
 [139. 154.]]


In [18]:
# 跨维求和
x = np.array([[1,2],[3,4]])
print(x)
print("sum all: ", np.sum(x)) # 将所有元素相加
print("sum by col: ", np.sum(x, axis=0)) # 将每列的元素相加
print("sum by row: ", np.sum(x, axis=1)) # 将每行的元素相加

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


In [19]:
b = np.array([[1, 2], [3, 4]])
print(np.tile(b, 2))
print("")
print(np.tile(b, (2, 1)))


[[1 2 1 2]
 [3 4 3 4]]

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
